server:
  port: 9090
  servlet:
    context-path: /producer
spring:
  application:
    name: cloud-producer
  mvc:
    throw-exception-if-no-handler-found: true  #出现404错误，直接抛出异常
  resources:
    add-mappings: false


eureka:
  client:
    service-url:
      defaultZone: http://cloudmap:cloudmap@localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2  #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5  #超过5秒即熔断（默认90秒）
    ip-address: 192.168.2.14  #调用服务的ip
feign:
  hystrix:
    enabled: true  #开启Feign对Hystrix的支持