server:
  port: 10010
  servlet:
    context-path: /consumer
spring:
  application:
    name: cloud-consumer
  mvc:
    throw-exception-if-no-handler-found: true  #出现404错误，直接抛出异常
  resources:
    add-mappings: false
eureka:
  client:
    service-url:
      defaultZone: http://cloudmap:cloudmap@localhost:8888/eureka/
    register-with-eureka: true   #是否注册至euraka
    fetch-registry: true  #是否获取eureka中的服务
  instance:
    lease-renewal-interval-in-seconds: 2   #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5  #超过5秒即熔断
    ip-address: 192.168.2.14
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true  #开启Feign对Hystrix的支持